Typescript convert - Add rpc back in from ripple - Adjust Buffers - Adjust packages

diff --git a/docker/insight/Dockerfile b/docker/insight/Dockerfile
--- a/docker/insight/Dockerfile
+++ b/docker/insight/Dockerfile
@@ -1,82 +1,99 @@
-# Dockerfile for insight build found in docker-compose.yml
+# syntax=docker.io/docker/dockerfile:1
 
-FROM node:23-bullseye
+FROM node:23-alpine AS base
 
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 
-# Use production node environment by default.
-
-# ENV NODE_ENV production
-
-
-# Change working directory
-
-WORKDIR /insight-app
+# https://nathanfries.com/posts/docker-npm-workspaces/ fix for package-lock.json not found
 
 
-# Download dependencies as a separate step to take advantage of Docker's caching.
-# Leverage a cache mount to /root/.npm to speed up subsequent builds.
-# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
-# into this layer.
+# change working directory to /app/insight for base
 
-RUN --mount=type=bind,source=package.json,target=package.json \
-    --mount=type=bind,source=package-lock.json,target=package-lock.json \
-    --mount=type=cache,target=/root/.npm \
-    npm ci --omit=dev
+WORKDIR /app/thoughtcore-lib
 
-RUN addgroup --system --gid 1001 nodejs
-RUN adduser --system --uid 1001 insight
+# Install dependencies based on the preferred package manager
+COPY packages/thoughtcore-lib/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+# RUN \
+#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#   elif [ -f package-lock.json ]; then npm ci; \
+#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
+
+# Install deps for thoughtcore-lib
+
+RUN npm install
+
+# change working directory to /app/insight for base
+
+WORKDIR /app/insight
+
+# Install dependencies based on the preferred package manager
+COPY packages/insight/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+
+# RUN \
+#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#   elif [ -f package-lock.json ]; then npm ci; \
+#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
+
+# Install deps for insight
+RUN npm install
 
 
-# Copy the rest of the source files into the image. Context is handled by docker-compose.yml in monorepo root
-
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/thoughtcore-lib/node_modules ./thoughtcore-lib/node_modules
+COPY --from=deps /app/insight/node_modules ./insight/node_modules
+COPY --from=deps /app/insight/package-lock.json ./insight/package-lock.json
 COPY ./packages/insight ./insight
 COPY ./packages/thoughtcore-lib ./thoughtcore-lib
-COPY ./packages/thoughtcore-build ./thoughtcore-build
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED=1
+
+WORKDIR /app/insight
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 
-# Change working directory and install
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-WORKDIR /insight-app/thoughtcore-build
-RUN npm install --ignore-scripts
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED=1
 
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-# Change working directory and install
+COPY --from=builder /app/insight/public ./public
 
-WORKDIR /insight-app/thoughtcore-lib
-RUN npm install --ignore-scripts
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/insight/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/insight/.next/static ./.next/static
 
+USER nextjs
 
-# Change working directory and install
+EXPOSE 3000
 
-WORKDIR /insight-app/insight
-RUN npm install --ignore-scripts
+ENV PORT=3000
 
-# Actually build the application
-
-RUN npm run build
-
-
-COPY public .next/standalone/ 
-COPY .next/static .next/standalone/.next/
-
-
-# Run the application as a non-root user.
-
-USER insight
-
-
-# Expose the port that the application listens on.
-
-# EXPOSE 3000
-
-
-# Set environment variables for nextjs
-
-# ENV PORT=3000
-# server.js is created by next build from the standalone output, see https://nextjs.org/docs/pages/api-reference/next-config-js/output
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
 # ENV HOSTNAME="0.0.0.0"
-
-
-# Run the application.
-
-CMD node .next/standalone/server.js
+CMD ["node", "server.js"]
diff --git a/docker/thoughtcore-node/Dockerfile b/docker/thoughtcore-node/Dockerfile
--- a/docker/thoughtcore-node/Dockerfile
+++ b/docker/thoughtcore-node/Dockerfile
@@ -1,74 +1,141 @@
-# Dockerfile for thoughtcore-node build found in docker-compose.yml
+# syntax=docker.io/docker/dockerfile:1
 
-FROM node:23-bullseye
+FROM node:23-alpine AS base
 
+# Dependencies stage
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+# https://nathanfries.com/posts/docker-npm-workspaces/ fix for package-lock.json not found
 
-# Install Chrome
+WORKDIR /app/thoughtcore-node
+COPY ./packages/thoughtcore-node/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
+WORKDIR /app/thoughtcore-lib
+COPY ./packages/thoughtcore-lib/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
+WORKDIR /app/thoughtcore-mnemonic
+COPY ./packages/thoughtcore-mnemonic/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-RUN set -x \
-    && apt-get update \
-    && apt-get install -y \
-    google-chrome-stable
+WORKDIR /app/thoughtcore-p2p
+COPY ./packages/thoughtcore-p2p/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-ENV CHROME_BIN /usr/bin/google-chrome
+WORKDIR /app/thoughtcore-wallet-client
+COPY ./packages/thoughtcore-wallet-client/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
+WORKDIR /app/thoughtcore-wallet-service
+COPY ./packages/thoughtcore-wallet-service/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-# Log versions
+WORKDIR /app/thoughtcore-client
+COPY ./packages/thoughtcore-client/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-RUN set -x \
-    && node -v \
-    && npm -v \
-    && google-chrome --version
+WORKDIR /app/crypto-wallet-core
+COPY ./packages/crypto-wallet-core/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
+WORKDIR /app/crypto-rpc
+COPY ./packages/crypto-rpc/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
-# Install npm version
-
-RUN npm i -g npm@10.9.2
-
-
-# Set container working directory to /thoughtcore
-
-WORKDIR /thoughtcore
-
-
-# Add sources, Context is handled by docker-compose.yml in monorepo root
-
-ADD . .
-
-# COPY lerna.json ./
-
-# COPY package*.json ./
-
-# COPY  ./packages/thoughtcore-client/package.json ./packages/thoughtcore-client/package.json
-
-# COPY  ./packages/thoughtcore-build/package.json ./packages/thoughtcore-build/package.json
-
-# COPY  ./packages/thoughtcore-lib/package.json ./packages/thoughtcore-lib/package.json
-
-# COPY  ./packages/thoughtcore-mnemonic/package.json ./packages/thoughtcore-mnemonic/package.json
-
-# COPY  ./packages/thoughtcore-node/package.json ./packages/thoughtcore-node/package.json
-
-# COPY  ./packages/thoughtcore-p2p/package.json ./packages/thoughtcore-p2p/package.json
-
-# COPY  ./packages/thoughtcore-wallet-client/package.json ./packages/thoughtcore-wallet-client/package.json
-
-# COPY  ./packages/thoughtcore-wallet-service/package.json ./packages/thoughtcore-wallet-service/package.json
-
-# COPY  ./packages/thoughtcore-wallet/package.json ./packages/thoughtcore-wallet/package.json
-
-# COPY  ./packages/crypto-wallet-core/package.json ./packages/crypto-wallet-core/package.json
+WORKDIR /app/thoughtd-rpc
+COPY ./packages/thoughtd-rpc/package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN npm install
 
 
-# Install npm dependencies
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
 
-RUN npm install --ignore-scripts
+COPY --from=deps /app/thoughtcore-client/node_modules ./thoughtcore-client/node_modules
+COPY --from=deps /app/thoughtcore-client/package-lock.json ./thoughtcore-client/package-lock.json
+
+COPY --from=deps /app/crypto-wallet-core/node_modules ./crypto-wallet-core/node_modules
+COPY --from=deps /app/crypto-wallet-core/package-lock.json ./crypto-wallet-core/package-lock.json
+
+COPY --from=deps /app/thoughtcore-node/node_modules ./thoughtcore-node/node_modules
+COPY --from=deps /app/thoughtcore-node/package-lock.json ./thoughtcore-node/package-lock.json
+
+COPY --from=deps /app/thoughtcore-lib/node_modules ./thoughtcore-lib/node_modules
+COPY --from=deps /app/thoughtcore-mnemonic/node_modules ./thoughtcore-mnemonic/node_modules
+COPY --from=deps /app/thoughtcore-p2p/node_modules ./thoughtcore-p2p/node_modules
+COPY --from=deps /app/thoughtcore-wallet-client/node_modules ./thoughtcore-wallet-client/node_modules
+COPY --from=deps /app/thoughtcore-wallet-service/node_modules ./thoughtcore-wallet-service/node_modules
+COPY --from=deps /app/crypto-rpc/node_modules ./crypto-rpc/node_modules
+COPY --from=deps /app/thoughtd-rpc/node_modules ./thoughtd-rpc/node_modules
+
+COPY ./packages/thoughtcore-client ./thoughtcore-client
+COPY ./packages/crypto-wallet-core ./crypto-wallet-core
+COPY ./packages/thoughtcore-node ./thoughtcore-node
+
+COPY ./packages/thoughtcore-lib ./thoughtcore-lib
+COPY ./packages/thoughtcore-mnemonic ./thoughtcore-mnemonic
+COPY ./packages/thoughtcore-p2p ./thoughtcore-p2p
+COPY ./packages/thoughtcore-wallet-client ./thoughtcore-wallet-client
+COPY ./packages/thoughtcore-wallet-service ./thoughtcore-wallet-service
+COPY ./packages/crypto-rpc ./crypto-rpc
+COPY ./packages/thoughtd-rpc ./thoughtd-rpc
+
+WORKDIR /app/crypto-wallet-core
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+WORKDIR /app/thoughtcore-client
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+WORKDIR /app/thoughtcore-node
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 
-# Compile dpendencies
+# Production stage
+FROM base AS runner
+WORKDIR /app/thoughtcore-node
 
-RUN npm run compile
+ENV NODE_ENV=production
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 expressjs
+
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-node/build/src ./
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-node/thoughtcore-config.json ./
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-node/node_modules ./node_modules
+
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-lib ./node_modules/thoughtcore-lib
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-p2p ./node_modules/thoughtcore-p2p
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-client ./node_modules/thoughtcore-client
+COPY --from=builder --chown=expressjs:nodejs /app/crypto-wallet-core ./node_modules/crypto-wallet-core
+COPY --from=builder --chown=expressjs:nodejs /app/crypto-rpc ./node_modules/crypto-rpc
+COPY --from=builder --chown=expressjs:nodejs /app/thoughtcore-wallet-client ./node_modules/thoughtcore-wallet-client
+
+
+EXPOSE 3004
+
+ENV PORT=3004
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+
+CMD ["node", "server.js"]
